export const GENRE_SCORES = [
  { genre_id: 12, genre_name: '모험', score: 0, count: 0 },
  { genre_id: 14, genre_name: '판타지', score: 0, count: 0 },
  { genre_id: 16, genre_name: '애니메이션', score: 0, count: 0 },
  { genre_id: 18, genre_name: '드라마', score: 0, count: 0 },
  { genre_id: 27, genre_name: '공포', score: 0, count: 0 },
  { genre_id: 28, genre_name: '액션', score: 0, count: 0 },
  { genre_id: 35, genre_name: '코미디', score: 0, count: 0 },
  { genre_id: 36, genre_name: '역사', score: 0, count: 0 },
  { genre_id: 37, genre_name: '서부', score: 0, count: 0 },
  { genre_id: 53, genre_name: '스릴러', score: 0, count: 0 },
  { genre_id: 80, genre_name: '범죄', score: 0, count: 0 },
  { genre_id: 99, genre_name: '다큐멘터리', score: 0, count: 0 },
  { genre_id: 878, genre_name: 'SF', score: 0, count: 0 },
  { genre_id: 9648, genre_name: '미스터리', score: 0, count: 0 },
  { genre_id: 10402, genre_name: '음악', score: 0, count: 0 },
  { genre_id: 10749, genre_name: '로맨스', score: 0, count: 0 },
  { genre_id: 10751, genre_name: '가족', score: 0, count: 0 },
  { genre_id: 10752, genre_name: '전쟁', score: 0, count: 0 },
  { genre_id: 10759, genre_name: '어드벤처', score: 0, count: 0 },
  { genre_id: 10762, genre_name: '키드', score: 0, count: 0 },
  { genre_id: 10763, genre_name: '뉴스', score: 0, count: 0 },
  { genre_id: 10764, genre_name: '리얼리티', score: 0, count: 0 },
  { genre_id: 10765, genre_name: '판타지', score: 0, count: 0 },
  { genre_id: 10766, genre_name: '댄스', score: 0, count: 0 },
  { genre_id: 10767, genre_name: '토크', score: 0, count: 0 },
  { genre_id: 10768, genre_name: '정치', score: 0, count: 0 },
  { genre_id: 10770, genre_name: 'TV 영화', score: 0, count: 0 },
];
