export const GENRE_SCORES = [
  { GENRE_CODE: 12, GENRE_NAME: '모험', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 14, GENRE_NAME: '판타지', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 16, GENRE_NAME: '애니메이션', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 18, GENRE_NAME: '드라마', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 27, GENRE_NAME: '공포', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 28, GENRE_NAME: '액션', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 35, GENRE_NAME: '코미디', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 36, GENRE_NAME: '역사', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 37, GENRE_NAME: '서부', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 53, GENRE_NAME: '스릴러', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 80, GENRE_NAME: '범죄', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 99, GENRE_NAME: '다큐멘터리', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 878, GENRE_NAME: 'SF', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 9648, GENRE_NAME: '미스터리', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10402, GENRE_NAME: '음악', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10749, GENRE_NAME: '로맨스', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10751, GENRE_NAME: '가족', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10752, GENRE_NAME: '전쟁', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10759, GENRE_NAME: '어드벤처', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10762, GENRE_NAME: '키드', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10763, GENRE_NAME: '뉴스', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10764, GENRE_NAME: '리얼리티', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10765, GENRE_NAME: '판타지', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10766, GENRE_NAME: '댄스', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10767, GENRE_NAME: '토크', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10768, GENRE_NAME: '정치', SCORE: 0, COUNT: 0 },
  { GENRE_CODE: 10770, GENRE_NAME: 'TV 영화', SCORE: 0, COUNT: 0 },
];

export const getGenreName = (genreCode) => {
  for (const genre of GENRE_SCORES) {
    if (genreCode === genre.GENRE_CODE) return genre.GENRE_NAME;
  }
};
